### ISSUE TITLE
Consider adding support for "onlyCurrent=False" URI parameter  to Get-BambooHRDirectory & Get-BambooHRUser

### ISSUE THREAD

**Issue by jbosloy** [simonxciv/Bamboozled#5]
The default behavior is that only current information is returned. Some fields, such as department and supervisor, are not returned until the employee start date is reached. However, if you add the query parameter "onlyCurrent=False" to the URI then non-current (e.g. future information) is returned. Of course, has to be used only when you want future information, such as for new hires before their hire date.

So. this could be a new option to the API entry point to request non-current information when it is needed.

So, this enhancement request may be useful.

From the BambooHR API change log for 2016.09:

FUTURE DATING
Currently, any time you future date a hire date, termination date, or tabular data (Job Information, Compensation etc.) we recognize that information in Bamboo immediately. With the coming change we will only recognize the date when the date arrives.

**Comment by turbo-donkey** [comment]
Seconded.  Having this exact problem using Bamboo to create new AD users before the start date and the above is the suggested answer from Bamboo.

**Comment by aubrey-wodonga** [comment]
Fixed in #7
